name: Slack

on:
  workflow_run: # ①ワークフローの実行によって発生するイベント
    workflows: ["Node.js CI"] # ここに書いたワークフローの実行により新しくワークフローを開始できる
    types: # ② 特定のタイミングでワークフローを実行する
      - completed # requested: ワークフローの開始が要求された時に発生する
      # completed: ワークフローが完了した時に発生する

jobs:
  slack:
    if: github.event.workflow_run.conclusion == 'failure' # ③ if: 指定した条件を満たした時だけジョブを実行する
    # github.event.workflow_run.conclusion == 'failure': ワークフローが失敗した時だけジョブが実行
    runs-on: ubuntu-latest
    steps:
      # https://zenn.dev/shonansurvivors/articles/fab832f7bfa8cebac24f
      - name: Notify CI Error
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: プルリクエスト時のCI処理結果
          fields: repo,message,commit,author,action,job,took,eventName,ref,workflow
          mention: "subteam^U01HWP9SJDP" # 追加
          if_mention: failure # 追加
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

    # https://neos21.net/blog/2021/02/19-01.html
    #   - uses: rtCamp/action-slack-notify@v2
    #     env:
    #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #       SLACK_USERNAME: My Alert
    #       SLACK_ICON_EMOJI: ":github:"
    #       SLACK_COLOR: danger
    #       SLACK_TITLE: タイトル
    #       SLACK_MESSAGE: メッセージ
    #   - uses: miyajin/action-slack-workflow_run@v1.0.0 # ④slackに通知するアクション
    #     with:
    #       slack-webhook-url: ${{secrets.SLACK_WEBHOOK_URL}} # ⑤
    # #       # https://qiita.com/Daara_y/items/b23bce4c0a2f763451b1#slack%E3%81%AEwebhookurl%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B
